import { Product } from '../types';

export const INITIAL_PRODUCTS: Product[] = [
  // GROCERIES & FOOD
  {
    id: 'prod-beef-meat',
    name: 'Beef (With Bone / Steak)',
    swahiliName: 'Nyama ya Ng\'ombe',
    aliases: ['nyama', 'beef', 'meat', 'nyama ya ngombe', 'steak', 'nyama choma raw', 'ng\'ombe'],
    category: 'groceries',
    subcategory: 'Meat & Poultry',
    sizeOrQuantity: '1 kg',
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 620,
    minPrice: 550,
    maxPrice: 720,
    priceType: 'MARKET_RETAIL',
    county: 'Nairobi',
    town: 'Nairobi',
    area: 'City Market / Burma Market & Local Butcheries',
    retailerOrSource: 'Nairobi Butchery Index / Kenya Meat Commission',
    dateCollected: 'Today',
    reportsCount: 42,
    confirmsCount: 118,
    outdatesCount: 3,
    flaggedCount: 1,
    sourceUrl: 'https://knbs.or.ke',
    description: 'Fresh grade-standard beef per kilogram. Butcheries in estates typically charge 580–640 KSh; City Market and upscale supermarkets charge 680–720 KSh.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-chicken-kuku',
    name: 'Whole Chicken (Broiler / Kienyeji)',
    swahiliName: 'Kuku Mzima',
    aliases: ['kuku', 'chicken', 'broiler', 'kienyeji', 'kuku kienyeji', 'kuku wa nyama', 'poultry'],
    category: 'groceries',
    subcategory: 'Meat & Poultry',
    sizeOrQuantity: '1.2 kg - 1.5 kg',
    unit: 'bird',
    image: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 550,
    minPrice: 480,
    maxPrice: 900,
    priceType: 'MARKET_RETAIL',
    county: 'Nairobi',
    town: 'Kariokor / City Center',
    area: 'City Poultry Market',
    retailerOrSource: 'Kariokor Poultry Market & Supermarkets',
    dateCollected: 'This Week',
    reportsCount: 35,
    confirmsCount: 89,
    outdatesCount: 2,
    flaggedCount: 0,
    description: 'Dressed broiler chicken averages 500–600 KSh. Authentic local Kienyeji chickens typically fetch 850–1,100 KSh depending on size and market.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-sugar-sukari',
    name: 'White Sugar (Kabras / Mumias)',
    swahiliName: 'Sukari Nyeupe',
    aliases: ['sukari', 'sugar', 'white sugar', 'kabras', 'mumias', 'ndhiwa', 'sukari ya chai'],
    category: 'groceries',
    subcategory: 'Pantry',
    sizeOrQuantity: '1 kg packet',
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1581441363689-1f3c3c414635?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 185,
    minPrice: 170,
    maxPrice: 210,
    priceType: 'MARKET_RETAIL',
    county: 'Nairobi',
    town: 'Nairobi',
    area: 'National Retail Stores & Kiosks',
    retailerOrSource: 'Carrefour Kenya / Naivas / Quickmart Average',
    dateCollected: 'Today',
    reportsCount: 88,
    confirmsCount: 240,
    outdatesCount: 6,
    flaggedCount: 2,
    description: '1kg locally milled sugar. Estate kiosks range between 180–200 KSh; 2kg packets retail around 350–390 KSh.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-watermelon-tikiti',
    name: 'Fresh Sweet Watermelon',
    swahiliName: 'Tikitimaji / Tikiti Maji',
    aliases: ['watermelon', 'water melon', 'tikiti', 'tikitimaji', 'tikiti maji', 'melons'],
    category: 'groceries',
    subcategory: 'Fruits & Veg',
    sizeOrQuantity: '1 kg / medium whole (approx 4-5kg)',
    unit: 'kg',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 65,
    minPrice: 50,
    maxPrice: 85,
    priceType: 'MARKET_RETAIL',
    county: 'Nairobi',
    town: 'Nairobi',
    area: 'Marikiti (Wakulima Market) & Estate Grocers',
    retailerOrSource: 'Wakulima Market Wholesale Index',
    dateCollected: 'Yesterday',
    reportsCount: 19,
    confirmsCount: 52,
    outdatesCount: 1,
    flaggedCount: 0,
    description: 'Sold at 50–70 KSh per kilogram at roadside and open-air markets. A whole medium watermelon (4-5kg) costs roughly 250–320 KSh.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-bottled-water',
    name: 'Bottled Drinking Water (Keringet / Dasani / Aquafresh)',
    swahiliName: 'Maji ya Chupa ya Kunywa',
    aliases: ['bottled water', 'water', 'maji', 'drinking water', 'mineral water', 'dasani', 'keringet', 'maji ya chupa'],
    category: 'groceries',
    subcategory: 'Beverages',
    sizeOrQuantity: '1 Litre bottle',
    unit: 'litre',
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 60,
    minPrice: 50,
    maxPrice: 90,
    priceType: 'MARKET_RETAIL',
    county: 'Nairobi',
    town: 'Nairobi',
    area: 'Supermarkets & Kiosks',
    retailerOrSource: 'Retailer Shelf Surveys',
    dateCollected: 'This Week',
    reportsCount: 22,
    confirmsCount: 77,
    outdatesCount: 0,
    flaggedCount: 0,
    description: '1L purified still drinking water. 500ml costs 30–40 KSh; 20-litre refill jugs at refill stations cost 150–250 KSh.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-maize-flour-unga',
    name: 'Maize Meal Flour (Soko / Jogoo / Raha Premium)',
    swahiliName: 'Unga wa Ugali',
    aliases: ['unga', 'unga wa ugali', 'maize flour', 'jogoo', 'soko', 'pembe', 'hostess', 'ugali flour'],
    category: 'groceries',
    subcategory: 'Pantry',
    sizeOrQuantity: '2 kg packet',
    unit: '2kg packet',
    image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 155,
    minPrice: 140,
    maxPrice: 180,
    priceType: 'MARKET_RETAIL',
    county: 'Nairobi',
    town: 'All Counties',
    area: 'Nationwide Stores',
    retailerOrSource: 'Ministry of Agriculture & Retail Survey',
    dateCollected: 'Today',
    reportsCount: 95,
    confirmsCount: 310,
    outdatesCount: 5,
    flaggedCount: 0,
    description: 'Standard 2kg packet of fortified sifted maize meal. Premium brands (e.g. Hostess, Amaize) sell between 190–220 KSh.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-milk-maziwa',
    name: 'Fresh Cow Milk (Brookside / KCC / Ilara)',
    swahiliName: 'Maziwa Safi ya Ng\'ombe',
    aliases: ['maziwa', 'milk', 'fresh milk', 'brookside', 'kcc', 'maziwa ya mfuko', 'maziwa lala'],
    category: 'groceries',
    subcategory: 'Dairy',
    sizeOrQuantity: '500 ml pouch',
    unit: 'pouch (500ml)',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 65,
    minPrice: 55,
    maxPrice: 75,
    priceType: 'MARKET_RETAIL',
    county: 'Nairobi',
    town: 'Nairobi',
    area: 'General Kiosks & Dairies',
    retailerOrSource: 'Kenya Dairy Board / Supermarket Index',
    dateCollected: 'Today',
    reportsCount: 64,
    confirmsCount: 195,
    outdatesCount: 1,
    flaggedCount: 0,
    description: 'Pasteurized 500ml pouch. Dispenser milk (milk ATM) in residential areas retails at 60–70 KSh per litre.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-cooking-oil',
    name: 'Cooking Vegetable Oil (Fresh Fri / Rina / Salit)',
    swahiliName: 'Mafuta ya Kupikia',
    aliases: ['cooking oil', 'mafuta ya kupikia', 'fresh fri', 'rina', 'salit', 'mafuta', 'golden fry'],
    category: 'groceries',
    subcategory: 'Pantry',
    sizeOrQuantity: '1 Litre bottle',
    unit: 'litre',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 280,
    minPrice: 260,
    maxPrice: 330,
    priceType: 'MARKET_RETAIL',
    county: 'Nairobi',
    town: 'Nairobi',
    area: 'Supermarkets & Wholesale',
    retailerOrSource: 'Consumer Price Index',
    dateCollected: 'This Week',
    reportsCount: 47,
    confirmsCount: 130,
    outdatesCount: 2,
    flaggedCount: 1,
    description: '1 litre refined vegetable palm/corn oil. 2-litre bottles retail at 530–590 KSh; 5-litre jerricans retail at 1,300–1,450 KSh.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-cooking-gas-6kg',
    name: 'Cooking Gas LPG Refill (Pro Gas / K-Gas / Afrigas)',
    swahiliName: 'Mtungi wa Gesi (Kujaza)',
    aliases: ['gas', 'cooking gas', 'lpg', 'pro gas', 'kgas', 'k-gas', 'gesi', 'mtungi wa gas', 'gas 6kg', 'refill gas'],
    category: 'groceries',
    subcategory: 'Energy & Fuels',
    sizeOrQuantity: '6 kg cylinder refill',
    unit: 'refill',
    image: 'https://images.unsplash.com/photo-1622322062573-0447ec15cb87?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 1250,
    minPrice: 1100,
    maxPrice: 1400,
    priceType: 'MARKET_RETAIL',
    county: 'Nairobi',
    town: 'Nairobi / Kiambu / Machakos',
    area: 'Local Gas Depots & Petrol Stations',
    retailerOrSource: 'EPRA Kenya & Estate Depots',
    dateCollected: 'Today',
    reportsCount: 58,
    confirmsCount: 182,
    outdatesCount: 4,
    flaggedCount: 1,
    description: 'Standard 6kg LPG refill. 13kg cylinder refills average 2,700–3,100 KSh depending on distributor brand.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-eggs-tray',
    name: 'Fresh Farm Eggs (Tray of 30)',
    swahiliName: 'Tray ya Mayai (Mayai 30)',
    aliases: ['mayai', 'eggs', 'egg', 'tray ya mayai', 'mayai ya kienyeji', 'boiled egg', 'eggs tray'],
    category: 'groceries',
    subcategory: 'Dairy & Poultry',
    sizeOrQuantity: '1 Tray (30 eggs)',
    unit: 'tray (30 pcs)',
    image: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 420,
    minPrice: 380,
    maxPrice: 480,
    priceType: 'MARKET_RETAIL',
    county: 'Nairobi',
    town: 'Kiambu / Nairobi',
    area: 'Wangige Wholesale Market / Neighborhood Kiosks',
    retailerOrSource: 'Wangige & Kariokor Market Reports',
    dateCollected: 'Today',
    reportsCount: 38,
    confirmsCount: 144,
    outdatesCount: 1,
    flaggedCount: 0,
    description: 'Whole tray of 30 Grade 1 brown eggs. Individual eggs at local kiosks sell for 15–20 KSh each; boiled egg with kachumbari on street sells for 25–30 KSh.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-bread-mkate',
    name: 'White Bread (Supaloaf / Broadways / Festo)',
    swahiliName: 'Mkate Mweupe',
    aliases: ['mkate', 'bread', 'supaloaf', 'broadways', 'festive', 'mkate wa ngano'],
    category: 'groceries',
    subcategory: 'Bakery',
    sizeOrQuantity: '400 grams',
    unit: 'loaf',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 65,
    minPrice: 60,
    maxPrice: 70,
    priceType: 'MARKET_RETAIL',
    county: 'Nairobi',
    town: 'Nationwide',
    area: 'All Stores & Duka',
    retailerOrSource: 'Bakers Association of Kenya',
    dateCollected: 'Today',
    reportsCount: 71,
    confirmsCount: 280,
    outdatesCount: 2,
    flaggedCount: 0,
    description: 'Standard 400g sliced sandwich bread. 800g family size loaf retails at 120–135 KSh.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // BUILDING & HARDWARE
  {
    id: 'prod-bamburi-cement',
    name: 'Bamburi Tembo Cement (32.5R / 42.5N)',
    swahiliName: 'Simiti ya Bamburi Tembo',
    aliases: ['cement', 'simiti', 'bamburi', 'tembo cement', 'blue triangle', 'savannah cement', 'ndovu', 'simiti mfuko'],
    category: 'hardware',
    subcategory: 'Building Materials',
    sizeOrQuantity: '50 kg bag',
    unit: '50kg bag',
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 680,
    minPrice: 640,
    maxPrice: 740,
    priceType: 'MARKET_RETAIL',
    county: 'Nairobi',
    town: 'Mombasa Road / Jogoo Road / Thika Road',
    area: 'Hardware Stores',
    retailerOrSource: 'Kenyan Hardware Suppliers Association',
    dateCollected: 'This Week',
    reportsCount: 54,
    confirmsCount: 165,
    outdatesCount: 2,
    flaggedCount: 0,
    description: 'Standard 50kg bag of 32.5 grade Portland Pozzolana cement. Transport costs vary by distance (approx 20–50 KSh per bag within 10km).',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-river-sand-lorry',
    name: 'Clean River Building Sand (Mchanga)',
    swahiliName: 'Mchanga wa Mto (Lori)',
    aliases: ['sand', 'mchanga', 'river sand', 'lorry ya mchanga', 'mchanga wa kujenga', 'building sand'],
    category: 'hardware',
    subcategory: 'Building Materials',
    sizeOrQuantity: '10-tonne lorry tipper',
    unit: '10-tonne tipper',
    image: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 22000,
    minPrice: 18000,
    maxPrice: 28000,
    priceType: 'MARKET_RETAIL',
    county: 'Nairobi',
    town: 'Machakos / Kajiado Source to Nairobi',
    area: 'Delivered On-site',
    retailerOrSource: 'Sand Harvesters & Transporters Forum',
    dateCollected: 'This Month',
    reportsCount: 14,
    confirmsCount: 38,
    outdatesCount: 1,
    flaggedCount: 0,
    description: 'Coarse clean river sand for structural concrete and plastering. Price includes delivery within Nairobi metro; 14-tonne trucks cost 28,000–35,000 KSh.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-mabati-dumuzas',
    name: 'Iron Sheets Mabati DumuZas / Box Profile',
    swahiliName: 'Mabati ya Kuezeka',
    aliases: ['mabati', 'iron sheets', 'dumuzas', 'box profile', 'mabati ya kuezeka', 'corrugated sheets', 'mr mabati', 'royal mabati'],
    category: 'hardware',
    subcategory: 'Roofing',
    sizeOrQuantity: 'Gauge 30 (2.5 meter / 3 meter)',
    unit: 'piece',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 850,
    minPrice: 750,
    maxPrice: 1200,
    priceType: 'MARKET_RETAIL',
    county: 'Nairobi',
    town: 'Industrial Area',
    area: 'Direct Manufacturer / Wholesalers',
    retailerOrSource: 'Mabati Rolling Mills (MRM) & Hardware Distributers',
    dateCollected: 'This Month',
    reportsCount: 23,
    confirmsCount: 61,
    outdatesCount: 1,
    flaggedCount: 0,
    description: 'Resin-coated and galvanized corrugated/box profile roofing sheets. Gauge 28 heavier gauge costs 1,050–1,250 KSh per piece.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // CLOTHING & ACCESSORIES
  {
    id: 'prod-socks-soksi',
    name: 'Cotton Sports & Dress Socks (Pack of 3)',
    swahiliName: 'Soksi za Pamba',
    aliases: ['socks', 'soksi', 'stockings', 'socks 3 pack', 'cotton socks', 'soksi za viatu'],
    category: 'clothing',
    subcategory: 'Footwear & Accessories',
    sizeOrQuantity: '3-pair bundle',
    unit: 'pack (3 pairs)',
    image: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 200,
    minPrice: 150,
    maxPrice: 350,
    priceType: 'COMMUNITY_REPORT',
    county: 'Nairobi',
    town: 'Nairobi CBD / Eastleigh / Gikomba',
    area: 'Street hawkers & Mitumba markets',
    retailerOrSource: 'Gikomba & Eastleigh Wholesale Stalls',
    dateCollected: 'Yesterday',
    reportsCount: 45,
    confirmsCount: 132,
    outdatesCount: 1,
    flaggedCount: 0,
    description: 'Comfortable stretch cotton ankle and calf socks. Street hawkers sell individual pairs for 50–70 KSh; 3 pairs bundle for 150–200 KSh.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-shoe-rack',
    name: 'Portable 4-Tier / 5-Tier Shoe Rack',
    swahiliName: 'Kabila ya Viatu / Rack ya Viatu',
    aliases: ['shoe rack', 'rack ya viatu', 'shelves ya viatu', 'shoe shelf', 'shoerack', 'shoe stand', 'rack'],
    category: 'furniture',
    subcategory: 'Home Storage',
    sizeOrQuantity: '4-Tier Metal/Fabric',
    unit: 'unit',
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 1200,
    minPrice: 900,
    maxPrice: 1800,
    priceType: 'MARKET_RETAIL',
    county: 'Nairobi',
    town: 'Kamukunji / Eastleigh',
    area: 'Kamukunji Open Market & Jumia Kenya',
    retailerOrSource: 'Kamukunji Wholesale Vendors',
    dateCollected: 'This Week',
    reportsCount: 31,
    confirmsCount: 94,
    outdatesCount: 0,
    flaggedCount: 0,
    description: 'Assemble-it-yourself steel tube & non-woven fabric shoe rack holding 12–16 pairs. Heavy duty wooden artisan shoe racks start at 3,500 KSh.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-mens-jeans',
    name: 'Men\'s Denim Jeans Trousers',
    swahiliName: 'Suruali ya Jeans',
    aliases: ['jeans', 'suruali ya jeans', 'denim', 'trousers', 'suruali', 'pants'],
    category: 'clothing',
    subcategory: 'Men\'s Wear',
    sizeOrQuantity: 'Standard Sizes 30-38',
    unit: 'piece',
    image: 'https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 1200,
    minPrice: 800,
    maxPrice: 2200,
    priceType: 'COMMUNITY_REPORT',
    county: 'Nairobi',
    town: 'Gikomba / Eastleigh / CBD Boutiques',
    area: 'Mitumba Camera & Boutiques',
    retailerOrSource: 'Gikomba First-Camera & High Street Retail',
    dateCollected: 'This Week',
    reportsCount: 39,
    confirmsCount: 110,
    outdatesCount: 2,
    flaggedCount: 0,
    description: 'Grade 1 camera selection denim jeans in Gikomba cost 800–1,200 KSh; brand new imported jeans in town boutiques sell for 1,500–2,500 KSh.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // ELECTRONICS
  {
    id: 'prod-ps5-console',
    name: 'Sony PlayStation 5 Console (Slim / Standard)',
    swahiliName: 'PlayStation 5 (PS5)',
    aliases: ['ps5', 'playstation 5', 'playstation', 'ps5 slim', 'sony ps5', 'gaming console', 'play station 5'],
    category: 'electronics',
    subcategory: 'Gaming',
    sizeOrQuantity: '1 TB Storage + 1 DualSense Controller',
    unit: 'unit',
    image: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 72000,
    minPrice: 66000,
    maxPrice: 85000,
    priceType: 'MARKET_RETAIL',
    county: 'Nairobi',
    town: 'Nairobi CBD / Westlands',
    area: 'Luthuli Avenue Electronics & Sarit Centre',
    retailerOrSource: 'Vivid Gold / Gametroniq / Luthuli Ave Stores',
    dateCollected: 'Yesterday',
    reportsCount: 28,
    confirmsCount: 74,
    outdatesCount: 3,
    flaggedCount: 0,
    description: 'PlayStation 5 Slim Digital edition sells around 66,000–70,000 KSh; Disc Edition with optical drive averages 72,000–76,000 KSh.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-samsung-a15',
    name: 'Samsung Galaxy A15 (4G / 128GB)',
    swahiliName: 'Simu ya Samsung Galaxy A15',
    aliases: ['samsung a15', 'galaxy a15', 'samsung phone', 'simu ya samsung', 'smartphone', 'simu', 'a15'],
    category: 'electronics',
    subcategory: 'Smartphones',
    sizeOrQuantity: '4GB RAM / 128GB Storage',
    unit: 'piece',
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 17500,
    minPrice: 16000,
    maxPrice: 20000,
    priceType: 'MARKET_RETAIL',
    county: 'Nairobi',
    town: 'Nairobi CBD / Moi Avenue',
    area: 'Official Brand Stores & Safaricom Shops',
    retailerOrSource: 'Safaricom Shop / Samsung Brand Store Index',
    dateCollected: 'Today',
    reportsCount: 41,
    confirmsCount: 129,
    outdatesCount: 1,
    flaggedCount: 0,
    description: 'Popular budget 5000mAh battery phone with Super AMOLED 90Hz display and 50MP camera. 6GB/128GB variant is approx 19,500 KSh.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-vitron-smart-tv',
    name: 'Vitron 32-inch Smart Android Frameless TV',
    swahiliName: 'TV ya Vitron Inchi 32 (Smart)',
    aliases: ['tv', 'vitron', 'television', 'smart tv', 'vitron 32', 'tv ya vitron', '32 inch tv', 'tivii'],
    category: 'electronics',
    subcategory: 'Home Entertainment',
    sizeOrQuantity: '32-inch LED Screen',
    unit: 'unit',
    image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 12500,
    minPrice: 11000,
    maxPrice: 14500,
    priceType: 'MARKET_RETAIL',
    county: 'Nairobi',
    town: 'Luthuli Avenue',
    area: 'Luthuli Electronics Dealers & Jumia',
    retailerOrSource: 'Luthuli Electronics Traders Hub',
    dateCollected: 'This Week',
    reportsCount: 36,
    confirmsCount: 104,
    outdatesCount: 2,
    flaggedCount: 0,
    description: 'Built-in Netflix, YouTube, WiFi & DVB-T2 free-to-air decoder. Non-smart digital versions sell for 9,500–10,500 KSh.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // PROFESSIONAL SERVICES
  {
    id: 'prod-fundi-wa-maji-plumber',
    name: 'Plumber Call-Out & Inspection (Fundi wa Maji)',
    swahiliName: 'Fundi wa Maji (Kurekebisha Bomba)',
    aliases: ['plumber', 'fundi wa maji', 'plumbing', 'bomba', 'fundi bomba', 'pipe repair', 'water leak', 'tap fix'],
    category: 'services',
    subcategory: 'Home Maintenance',
    sizeOrQuantity: 'Standard Call-out & Minor Fix',
    unit: 'service call',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 1000,
    minPrice: 500,
    maxPrice: 2000,
    priceType: 'COMMUNITY_REPORT',
    county: 'Nairobi',
    town: 'Nairobi Metro',
    area: 'Estate & Apartment Call-outs',
    retailerOrSource: 'Artisan Community Collective / Fundi Smart',
    dateCollected: 'This Week',
    reportsCount: 52,
    confirmsCount: 140,
    outdatesCount: 1,
    flaggedCount: 0,
    description: 'Estate plumber inspection and minor leak/tap replacement labor. Heavy works (new piping or toilet installation) range between 3,500–8,000 KSh excluding parts.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-fundi-wa-stima-electrician',
    name: 'Electrician Fault Finding & Installation',
    swahiliName: 'Fundi wa Stima',
    aliases: ['electrician', 'fundi wa stima', 'fundi stima', 'wiring', 'stima repair', 'socket fix', 'circuit breaker'],
    category: 'services',
    subcategory: 'Home Maintenance',
    sizeOrQuantity: 'Single point diagnosis / replacement',
    unit: 'service call',
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 1200,
    minPrice: 700,
    maxPrice: 2500,
    priceType: 'COMMUNITY_REPORT',
    county: 'Nairobi',
    town: 'All Towns',
    area: 'Residential & Commercial',
    retailerOrSource: 'Electrical Technicians Kenya Register',
    dateCollected: 'This Week',
    reportsCount: 37,
    confirmsCount: 108,
    outdatesCount: 0,
    flaggedCount: 0,
    description: 'Certified or experienced technician for diagnosing tripped breakers, socket burning, or lighting fixtures. Full house rewiring labor starts from 25,000 KSh.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-phone-screen-repair',
    name: 'Smartphone Screen Glass / Display Replacement',
    swahiliName: 'Kutengeneza Kioo cha Simu',
    aliases: ['phone repair', 'screen replacement', 'kutengeneza simu', 'kioo cha simu', 'display replacement', 'fundi wa simu'],
    category: 'services',
    subcategory: 'Electronics Repair',
    sizeOrQuantity: 'Mid-range Android Display (OLED/LCD)',
    unit: 'repair service',
    image: 'https://images.unsplash.com/photo-1588515724527-074a7a56616c?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 3000,
    minPrice: 2000,
    maxPrice: 6500,
    priceType: 'COMMUNITY_REPORT',
    county: 'Nairobi',
    town: 'Nairobi CBD',
    area: 'Imenti House / Veteran House / Tom Mboya St',
    retailerOrSource: 'Imenti House Technicians Directory',
    dateCollected: 'Yesterday',
    reportsCount: 29,
    confirmsCount: 88,
    outdatesCount: 1,
    flaggedCount: 0,
    description: 'Replacement of cracked display on common Tecno, Infinix, or Samsung A-series phones. High-end AMOLED or iPhone screens cost between 7,000–18,000 KSh.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // HOUSING & RENT
  {
    id: 'prod-bedsitter-rongai',
    name: 'Bedsitter Studio Apartment (Ongata Rongai)',
    swahiliName: 'Bedsitter Rongai',
    aliases: ['bedsitter rongai', 'bedsitter', 'rongai bedsitter', 'studio apartment', 'chumba rongai', 'single room rongai'],
    category: 'housing',
    subcategory: 'Rentals',
    sizeOrQuantity: 'Tiled self-contained with balcony & own token',
    unit: 'month',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 8500,
    minPrice: 6500,
    maxPrice: 12000,
    priceType: 'MARKET_RETAIL',
    county: 'Kajiado',
    town: 'Ongata Rongai',
    area: 'Rongai Maasai Lodge / Tuskys Stage / Tumaini',
    retailerOrSource: 'Rongai Property Caretaker Surveys',
    dateCollected: 'This Month',
    reportsCount: 66,
    confirmsCount: 182,
    outdatesCount: 4,
    flaggedCount: 0,
    description: 'Modern tiled bedsitter with steady borehole water, token meter, and perimeter wall. Deposit typically 1 month rent plus 1,500–2,500 KSh water/electricity deposit.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-bedsitter-roysambu',
    name: 'Bedsitter Studio Apartment (Roysambu / TRM)',
    swahiliName: 'Bedsitter Roysambu',
    aliases: ['bedsitter roysambu', 'roysambu bedsitter', 'trm bedsitter', 'kasarani bedsitter', 'bedsitter', 'studio roysambu'],
    category: 'housing',
    subcategory: 'Rentals',
    sizeOrQuantity: 'Self-contained ensuite studio',
    unit: 'month',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 11000,
    minPrice: 8500,
    maxPrice: 15000,
    priceType: 'MARKET_RETAIL',
    county: 'Nairobi',
    town: 'Roysambu',
    area: 'Behind TRM / Lumumba Drive',
    retailerOrSource: 'Thika Road Real Estate Index',
    dateCollected: 'This Month',
    reportsCount: 51,
    confirmsCount: 147,
    outdatesCount: 2,
    flaggedCount: 1,
    description: 'High-demand youth & university hub near TRM Mall and USIU. Comes with internet fiber provision and 24/7 security gate.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-one-bedroom-apartment',
    name: '1 Bedroom Modern Apartment (Ruaka / Kiambu Road)',
    swahiliName: 'Nyumba ya Chumba Kimoja (1 Bedroom)',
    aliases: ['one bedroom', '1 bedroom', 'ruaka 1 bedroom', 'chumba kimoja', 'apartment 1 bedroom', 'rent'],
    category: 'housing',
    subcategory: 'Rentals',
    sizeOrQuantity: 'Master ensuite with living room & kitchen',
    unit: 'month',
    image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 20000,
    minPrice: 16000,
    maxPrice: 28000,
    priceType: 'MARKET_RETAIL',
    county: 'Kiambu',
    town: 'Ruaka',
    area: 'Joyland / Slaughter / Ndenderu Link',
    retailerOrSource: 'Kiambu County Residential Property Review',
    dateCollected: 'This Month',
    reportsCount: 33,
    confirmsCount: 96,
    outdatesCount: 2,
    flaggedCount: 0,
    description: 'Spacious 1-bedroom with granite kitchen tops, elevator access, backup generator, and dedicated parking spot.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // TRANSPORT
  {
    id: 'prod-boda-boda-trip',
    name: 'Boda Boda Short Distance Ride (1–3 km)',
    swahiliName: 'Nauli ya Boda Boda',
    aliases: ['boda', 'boda boda', 'bodaboda', 'nauli ya boda', 'motorcycle ride', 'piki piki'],
    category: 'transport',
    subcategory: 'Local Transit',
    sizeOrQuantity: 'Short distance point-to-point',
    unit: 'trip',
    image: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 100,
    minPrice: 50,
    maxPrice: 150,
    priceType: 'COMMUNITY_REPORT',
    county: 'Nairobi',
    town: 'Nationwide Estate Stages',
    area: 'Stage to Estate Gate / House',
    retailerOrSource: 'Boda Boda Riders Association Average',
    dateCollected: 'Today',
    reportsCount: 84,
    confirmsCount: 242,
    outdatesCount: 3,
    flaggedCount: 0,
    description: 'Minimum base fare from main bus stage to residential estates is usually 50–100 KSh; late night or rainy weather rates rise to 150–200 KSh.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-sgr-train-ticket',
    name: 'Madaraka Express SGR Train (Nairobi ⇄ Mombasa)',
    swahiliName: 'Tiketi ya SGR Treni (Nairobi - Mombasa)',
    aliases: ['sgr', 'madaraka express', 'sgr ticket', 'train', 'treni', 'mombasa train', 'sgr fare'],
    category: 'transport',
    subcategory: 'Intercity Rail',
    sizeOrQuantity: 'One-way Economy Class Seat',
    unit: 'passenger ticket',
    image: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 1500,
    minPrice: 1500,
    maxPrice: 4500,
    priceType: 'VERIFIED_OFFICIAL',
    county: 'Nairobi',
    town: 'Syokimau / Miritini',
    area: 'Nairobi Terminus to Mombasa Terminus',
    retailerOrSource: 'Kenya Railways Corporation Official Gazette',
    dateCollected: 'Official 2024/2025 Tariff',
    reportsCount: 92,
    confirmsCount: 320,
    outdatesCount: 0,
    flaggedCount: 0,
    sourceUrl: 'https://krc.co.ke',
    description: 'Official Kenya Railways fare: Economy class is fixed at 1,500 KSh; First Class is fixed at 4,500 KSh. Children aged 3–11 travel half price.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },

  // BEAUTY & PERSONAL CARE
  {
    id: 'prod-kinyozi-haircut',
    name: 'Men\'s Executive Haircut & Beard Grooming',
    swahiliName: 'Kinyozi (Kunyoa Nywele & Ndevu)',
    aliases: ['kinyozi', 'haircut', 'barber', 'kunyoa', 'shave', 'beard trim', 'kinyozi executive'],
    category: 'beauty',
    subcategory: 'Barbershop',
    sizeOrQuantity: 'Haircut + Beard Shave + Head Wash',
    unit: 'session',
    image: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 300,
    minPrice: 150,
    maxPrice: 1000,
    priceType: 'COMMUNITY_REPORT',
    county: 'Nairobi',
    town: 'Nairobi',
    area: 'Local Estates & Commercial Hubs',
    retailerOrSource: 'Estate Kinyozi Barbers Index',
    dateCollected: 'This Week',
    reportsCount: 56,
    confirmsCount: 172,
    outdatesCount: 1,
    flaggedCount: 0,
    description: 'Local neighborhood barber shop haircut ranges between 150–300 KSh. Executive barbershops in malls or Kilimani charge 800–1,500 KSh.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 'prod-womens-braids-salon',
    name: 'Women\'s Box Braids / Knotless Braids (Salon Labor)',
    swahiliName: 'Kusuka Nywele (Box Braids / Knotless)',
    aliases: ['salon', 'braids', 'knotless', 'kusuka', 'box braids', 'lines', 'nywele', 'hair salon'],
    category: 'beauty',
    subcategory: 'Hair Styling',
    sizeOrQuantity: 'Medium length knotless braids styling (labor)',
    unit: 'hair session',
    image: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=600&q=80',
    typicalPrice: 1500,
    minPrice: 1000,
    maxPrice: 3500,
    priceType: 'COMMUNITY_REPORT',
    county: 'Nairobi',
    town: 'Kenyatta Market / Local Estates',
    area: 'Kenyatta Market & Neighborhood Salons',
    retailerOrSource: 'Kenyatta Market Hair Braiders Collective',
    dateCollected: 'This Week',
    reportsCount: 44,
    confirmsCount: 122,
    outdatesCount: 2,
    flaggedCount: 0,
    description: 'Labor fee at Kenyatta Market or estate salon. Braiding hair extensions (Darling / Abuja braid packets) purchased separately at 200–350 KSh per pack.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];

// Helper to create timestamp days ago
const daysAgo = (days: number): string => {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d.toISOString();
};

export const INITIAL_COMMUNITY_REPORTS = [
  // Beef reports
  {
    id: 'rep-beef-1',
    productId: 'prod-beef-meat',
    productName: 'Beef (With Bone / Steak)',
    reportedPrice: 580,
    unit: 'kg',
    quantity: '1 kg',
    county: 'Nairobi',
    town: 'Nairobi',
    area: 'Burma Market Butchery',
    storeName: 'Burma Wholesale Meat',
    purchaseDate: '3 weeks ago',
    notes: 'Bought raw with bone for soup',
    createdAt: daysAgo(21)
  },
  {
    id: 'rep-beef-2',
    productId: 'prod-beef-meat',
    productName: 'Beef (With Bone / Steak)',
    reportedPrice: 600,
    unit: 'kg',
    quantity: '2 kg',
    county: 'Kiambu',
    town: 'Ruiru',
    area: 'Ruiru Town',
    storeName: 'Jikaze Butchery',
    purchaseDate: '2 weeks ago',
    notes: 'Fresh steak cut',
    createdAt: daysAgo(14)
  },
  {
    id: 'rep-beef-3',
    productId: 'prod-beef-meat',
    productName: 'Beef (With Bone / Steak)',
    reportedPrice: 650,
    unit: 'kg',
    quantity: '1 kg',
    county: 'Nairobi',
    town: 'Nairobi',
    area: 'South B Shopping Centre',
    storeName: 'Neema Prime Butchery',
    purchaseDate: '8 days ago',
    notes: 'Boneless tender steak',
    createdAt: daysAgo(8)
  },
  {
    id: 'rep-beef-4',
    productId: 'prod-beef-meat',
    productName: 'Beef (With Bone / Steak)',
    reportedPrice: 620,
    unit: 'kg',
    quantity: '1.5 kg',
    county: 'Nairobi',
    town: 'Nairobi',
    area: 'City Market',
    storeName: 'Stall 14 City Market',
    purchaseDate: '3 days ago',
    notes: 'Fresh morning cut',
    createdAt: daysAgo(3)
  },
  {
    id: 'rep-beef-5',
    productId: 'prod-beef-meat',
    productName: 'Beef (With Bone / Steak)',
    reportedPrice: 640,
    unit: 'kg',
    quantity: '1 kg',
    county: 'Kajiado',
    town: 'Ongata Rongai',
    area: 'Rongai Maasai Lodge',
    storeName: 'Kiserian Meat Den',
    purchaseDate: 'Yesterday',
    notes: 'Standard estate butchery',
    createdAt: daysAgo(1)
  },

  // Sugar reports
  {
    id: 'rep-sugar-1',
    productId: 'prod-sugar-sukari',
    productName: 'White Sugar (Kabras / Mumias)',
    reportedPrice: 210,
    unit: 'kg',
    quantity: '1 kg',
    county: 'Nairobi',
    town: 'Nairobi',
    area: 'Kilimani',
    storeName: 'Chandarana Foodplus',
    purchaseDate: '3 weeks ago',
    notes: 'Kabras fortified 1kg',
    createdAt: daysAgo(22)
  },
  {
    id: 'rep-sugar-2',
    productId: 'prod-sugar-sukari',
    productName: 'White Sugar (Kabras / Mumias)',
    reportedPrice: 195,
    unit: 'kg',
    quantity: '1 kg',
    county: 'Nakuru',
    town: 'Nakuru',
    area: 'Kenyatta Avenue',
    storeName: 'Gilani Supermarket',
    purchaseDate: '2 weeks ago',
    notes: 'Local mill brand',
    createdAt: daysAgo(15)
  },
  {
    id: 'rep-sugar-3',
    productId: 'prod-sugar-sukari',
    productName: 'White Sugar (Kabras / Mumias)',
    reportedPrice: 185,
    unit: 'kg',
    quantity: '1 kg',
    county: 'Nairobi',
    town: 'Nairobi',
    area: 'CBD',
    storeName: 'Naivas Supermarket',
    purchaseDate: '6 days ago',
    notes: 'On weekly promotion',
    createdAt: daysAgo(6)
  },
  {
    id: 'rep-sugar-4',
    productId: 'prod-sugar-sukari',
    productName: 'White Sugar (Kabras / Mumias)',
    reportedPrice: 180,
    unit: 'kg',
    quantity: '1 kg',
    county: 'Nairobi',
    town: 'Nairobi',
    area: 'Pipeline',
    storeName: 'Estate Wholesale Duka',
    purchaseDate: 'Yesterday',
    notes: 'Loose weighed sugar',
    createdAt: daysAgo(1)
  },

  // Cement reports
  {
    id: 'rep-cement-1',
    productId: 'prod-bamburi-cement',
    productName: 'Bamburi Tembo Cement (32.5R / 42.5N)',
    reportedPrice: 720,
    unit: '50kg bag',
    quantity: '10 bags',
    county: 'Kiambu',
    town: 'Ruaka',
    area: 'Ruaka Bypass',
    storeName: 'Ruaka Hardware Supplies',
    purchaseDate: '4 weeks ago',
    notes: 'Included offloading labor',
    createdAt: daysAgo(28)
  },
  {
    id: 'rep-cement-2',
    productId: 'prod-bamburi-cement',
    productName: 'Bamburi Tembo Cement (32.5R / 42.5N)',
    reportedPrice: 690,
    unit: '50kg bag',
    quantity: '20 bags',
    county: 'Nairobi',
    town: 'Nairobi',
    area: 'Jogoo Road',
    storeName: 'Jogoo Hardware Hub',
    purchaseDate: '2 weeks ago',
    notes: '32.5 grade Tembo',
    createdAt: daysAgo(14)
  },
  {
    id: 'rep-cement-3',
    productId: 'prod-bamburi-cement',
    productName: 'Bamburi Tembo Cement (32.5R / 42.5N)',
    reportedPrice: 675,
    unit: '50kg bag',
    quantity: '50 bags',
    county: 'Machakos',
    town: 'Mlolongo',
    area: 'Mombasa Road',
    storeName: 'Wholesale Building Mart',
    purchaseDate: '5 days ago',
    notes: 'Bulk discount rate',
    createdAt: daysAgo(5)
  },
  {
    id: 'rep-cement-4',
    productId: 'prod-bamburi-cement',
    productName: 'Bamburi Tembo Cement (32.5R / 42.5N)',
    reportedPrice: 680,
    unit: '50kg bag',
    quantity: '5 bags',
    county: 'Nairobi',
    town: 'Nairobi',
    area: 'Roysambu',
    storeName: 'Kasarani Builders Mart',
    purchaseDate: 'Today',
    notes: 'Standard retail',
    createdAt: daysAgo(0)
  },

  // PS5 reports
  {
    id: 'rep-ps5-1',
    productId: 'prod-ps5-console',
    productName: 'Sony PlayStation 5 Console (Slim / Standard)',
    reportedPrice: 76000,
    unit: 'unit',
    quantity: '1 unit',
    county: 'Nairobi',
    town: 'Westlands',
    area: 'Sarit Centre',
    storeName: 'Anisuma Electronics',
    purchaseDate: '1 month ago',
    notes: 'Standard disc edition with 1 controller',
    createdAt: daysAgo(30)
  },
  {
    id: 'rep-ps5-2',
    productId: 'prod-ps5-console',
    productName: 'Sony PlayStation 5 Console (Slim / Standard)',
    reportedPrice: 73000,
    unit: 'unit',
    quantity: '1 unit',
    county: 'Nairobi',
    town: 'Nairobi CBD',
    area: 'Moi Avenue',
    storeName: 'GameStop Kenya (CBD)',
    purchaseDate: '2 weeks ago',
    notes: 'Slim digital version + extra controller',
    createdAt: daysAgo(14)
  },
  {
    id: 'rep-ps5-3',
    productId: 'prod-ps5-console',
    productName: 'Sony PlayStation 5 Console (Slim / Standard)',
    reportedPrice: 70000,
    unit: 'unit',
    quantity: '1 unit',
    county: 'Nairobi',
    town: 'Nairobi CBD',
    area: 'Luthuli Avenue',
    storeName: 'Luthuli Gaming Direct',
    purchaseDate: '4 days ago',
    notes: 'Slim 1TB disc edition, 1 yr warranty',
    createdAt: daysAgo(4)
  },

  // Plumber reports
  {
    id: 'rep-plumber-1',
    productId: 'prod-fundi-wa-maji-plumber',
    productName: 'Plumber Call-Out & Inspection (Fundi wa Maji)',
    reportedPrice: 800,
    unit: 'service call',
    quantity: '1 service call',
    county: 'Nairobi',
    town: 'Nairobi',
    area: 'Donholm',
    storeName: 'Fundi Dennis',
    purchaseDate: '3 weeks ago',
    notes: 'Fixed leaking kitchen sink connector',
    createdAt: daysAgo(20)
  },
  {
    id: 'rep-plumber-2',
    productId: 'prod-fundi-wa-maji-plumber',
    productName: 'Plumber Call-Out & Inspection (Fundi wa Maji)',
    reportedPrice: 1200,
    unit: 'service call',
    quantity: '1 service call',
    county: 'Nairobi',
    town: 'Nairobi',
    area: 'Kilimani',
    storeName: 'Fundi Smart Plumbing',
    purchaseDate: '10 days ago',
    notes: 'Replaced bathroom shower mixer valve',
    createdAt: daysAgo(10)
  },
  {
    id: 'rep-plumber-3',
    productId: 'prod-fundi-wa-maji-plumber',
    productName: 'Plumber Call-Out & Inspection (Fundi wa Maji)',
    reportedPrice: 1000,
    unit: 'service call',
    quantity: '1 service call',
    county: 'Kajiado',
    town: 'Ongata Rongai',
    area: 'Maasai Lodge Road',
    storeName: 'Fundi Joseph (Estate)',
    purchaseDate: '2 days ago',
    notes: 'Diagnosed slow toilet cistern filling',
    createdAt: daysAgo(2)
  },

  // Rongai Bedsitter reports
  {
    id: 'rep-bedsitter-1',
    productId: 'prod-bedsitter-rongai',
    productName: 'Bedsitter Studio Apartment (Ongata Rongai)',
    reportedPrice: 8000,
    unit: 'month',
    quantity: '1 month',
    county: 'Kajiado',
    town: 'Ongata Rongai',
    area: 'Tumaini Area',
    storeName: 'Grace Heights Apartments',
    purchaseDate: '2 months ago',
    notes: 'Includes free borehole water',
    createdAt: daysAgo(45)
  },
  {
    id: 'rep-bedsitter-2',
    productId: 'prod-bedsitter-rongai',
    productName: 'Bedsitter Studio Apartment (Ongata Rongai)',
    reportedPrice: 8500,
    unit: 'month',
    quantity: '1 month',
    county: 'Kajiado',
    town: 'Ongata Rongai',
    area: 'Maasai Lodge Stage',
    storeName: 'GreenView Court',
    purchaseDate: '1 month ago',
    notes: 'Own token meter and balcony',
    createdAt: daysAgo(25)
  },
  {
    id: 'rep-bedsitter-3',
    productId: 'prod-bedsitter-rongai',
    productName: 'Bedsitter Studio Apartment (Ongata Rongai)',
    reportedPrice: 9000,
    unit: 'month',
    quantity: '1 month',
    county: 'Kajiado',
    town: 'Ongata Rongai',
    area: 'Near Nazarene / Rimpa',
    storeName: 'Pinnacle Studios',
    purchaseDate: '5 days ago',
    notes: 'Tiled, WiFi ready, 24hr security',
    createdAt: daysAgo(5)
  },

  // Socks reports
  {
    id: 'rep-socks-1',
    productId: 'prod-socks-soksi',
    productName: 'Cotton Sports & Dress Socks (Pack of 3)',
    reportedPrice: 200,
    unit: 'pack (3 pairs)',
    quantity: '3 pairs',
    county: 'Nairobi',
    town: 'Nairobi CBD',
    area: 'Moi Avenue Hawkers',
    storeName: 'Street Hawker',
    purchaseDate: '2 weeks ago',
    notes: 'Thick sports ankle socks',
    createdAt: daysAgo(14)
  },
  {
    id: 'rep-socks-2',
    productId: 'prod-socks-soksi',
    productName: 'Cotton Sports & Dress Socks (Pack of 3)',
    reportedPrice: 150,
    unit: 'pack (3 pairs)',
    quantity: '3 pairs',
    county: 'Nairobi',
    town: 'Eastleigh',
    area: 'Garissa Lodge Mall',
    storeName: 'Eastleigh Wholesale Stall',
    purchaseDate: '6 days ago',
    notes: 'Bargained down from 180',
    createdAt: daysAgo(6)
  },
  {
    id: 'rep-socks-3',
    productId: 'prod-socks-soksi',
    productName: 'Cotton Sports & Dress Socks (Pack of 3)',
    reportedPrice: 200,
    unit: 'pack (3 pairs)',
    quantity: '3 pairs',
    county: 'Nairobi',
    town: 'Gikomba',
    area: 'Gikomba Market',
    storeName: 'Mitumba Camera Seller',
    purchaseDate: 'Yesterday',
    notes: 'Cotton dress socks',
    createdAt: daysAgo(1)
  },

  // Shoe Rack reports
  {
    id: 'rep-shoerack-1',
    productId: 'prod-shoe-rack',
    productName: 'Portable 4-Tier / 5-Tier Shoe Rack',
    reportedPrice: 1350,
    unit: 'unit',
    quantity: '1 unit',
    county: 'Nairobi',
    town: 'Nairobi',
    area: 'South C',
    storeName: 'Estate Household Shop',
    purchaseDate: '3 weeks ago',
    notes: '4-tier steel tube rack',
    createdAt: daysAgo(21)
  },
  {
    id: 'rep-shoerack-2',
    productId: 'prod-shoe-rack',
    productName: 'Portable 4-Tier / 5-Tier Shoe Rack',
    reportedPrice: 1100,
    unit: 'unit',
    quantity: '1 unit',
    county: 'Nairobi',
    town: 'Nairobi',
    area: 'Kamukunji Market',
    storeName: 'Kamukunji Open Trader',
    purchaseDate: '8 days ago',
    notes: 'Wholesale direct price',
    createdAt: daysAgo(8)
  },
  {
    id: 'rep-shoerack-3',
    productId: 'prod-shoe-rack',
    productName: 'Portable 4-Tier / 5-Tier Shoe Rack',
    reportedPrice: 1200,
    unit: 'unit',
    quantity: '1 unit',
    county: 'Nairobi',
    town: 'Nairobi',
    area: 'Eastleigh',
    storeName: 'Eastleigh 1st Avenue Duka',
    purchaseDate: '2 days ago',
    notes: 'Holds 16 pairs easily',
    createdAt: daysAgo(2)
  }
];
